[global]
pid = .lemp/cache/run/php-fpm.pid
error_log = .lemp/cache/logs/php-fpm.log
daemonize = no

[www]
listen = .lemp/cache/run/php-fpm.sock
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
