daemon off;

pid .lemp/cache/run/nginx.pid;
error_log .lemp/cache/logs/nginx-error.log;

events {}

http {
  include mime.types;
	default_type application/octet-stream;

  access_log .lemp/cache/logs/nginx-access.log;

  server {
    listen 8888 ssl;
    server_name localhost;

    include ssl.conf;

    location / {
      root www;
      index index.html index.htm index.php;
      autoindex on;
    }

    location ~ \.php$ {
      root www;
      include fastcgi.conf;
      fastcgi_pass unix:.lemp/cache/run/php-fpm.sock;
      fastcgi_index index.php;
    }

    location ^~ /. {
      deny all;
    }

    location /admin {
      alias .lemp/phpMyAdmin/;

      index index.php;

      location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_pass unix:.lemp/cache/run/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $request_filename;
      }
    }
  }
}
